version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  # Dockerfile Nginx
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
